# Generated by Django 4.1.3 on 2022-12-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('miles', models.IntegerField(max_length=10)),
                ('location', models.TextField(max_length=5000)),
                ('used_or_new', models.TextField(max_length=10)),
                ('price', models.IntegerField(max_length=500)),
                ('engine_type', models.TextField(max_length=5000)),
                ('Transmission', models.TextField(max_length=20)),
                ('fuel_type', models.TextField(max_length=6)),
                ('interior_color', models.TextField(max_length=20)),
                ('Exterior_color', models.TextField(max_length=20)),
                ('vehicle_id', models.TextField(max_length=50)),
            ],
        ),
    ]
